config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes

  root "recipes#index"  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	before_action :find_recipe, only: [:show, :edit, :update, :destroy]

	def index
		@recipes = Recipe.all
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)

		if @recipe.save
			redirect_to @recipe, notice: "Succesfully created new recipe"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render @recipe
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Succesfully deleted Recipe"
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end

	private

	def recipe_params
		params.require(:recipe).permit(:title,:description,:image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Recipie App
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
  %nav.navbar.navbar-default
    .container
      .nav-brand= link_to "Recipe Box", root_path

      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Recipe", new_recipe_path
        %li= link_to "Sign out", root_path


  .container
    - flash.each do |name,msg|
      = content_tag :div, msg, class: "alert"
    = yield	

app/views/recipes/_form.html.haml
=simple_form_for @recipe, html: { multipart: true } do |f|
	- if @recipe.errors.any?
		#errors
			%p
				= @recipe.errors.count
				Prevented this recipe froms saving
			%ul
				- @recipe.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		= f.input :title, input_html: { class: 'form-control' }
		= f.input :description, input_html: { class: 'form-control' }
		= f.input :image, input_html: { class: 'form-control' }
		= f.button :submit, class: "btn btn-primary"		

		/ = simple_form_for @recipe, html: {multipart: true} do |f|
/  - if @recipe.errors.any?
/   #errors 
/   %p
/    = @recipe.errors.count 
/    Prevent recipe from saving
/   %ul
/    - @recipe.errors.full_messages.each do |msg|
/    %li= msg
/   .panel-body
/    = f.input :title, input_html: { class: 'form-control'}
/    = f.input :description, input_html: { class: 'form-control'}

/   = f.button :submit, class: "btn btn-primary"		

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

= link_to "Back", @recipe

app/views/recipes/index.html.haml
- @recipes.each_slice(3) do |recipes|
 .row
  -recipes.each do |recipe|
   .col-md-4
    .recipe
     .image_wrapper
      = link_to recipe do
       = image_tag recipe.image.url(:medium)
     %h2= link_to recipe.title, recipe  

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'


= link_to 'Back', root_path, class: "btn btn-defult"

app/views/recipes/show.html.haml
= image_tag @recipe.image.url(:medium, class: "recipe_image")
%h1= @recipe.title
%p= @recipe.description

= link_to "Back", root_path, class: "btn btn-default"
= link_to "Edit", edit_recipe_path, class: "btn btn-default"
= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" 